### ISSUE TITLE
Nuget package Robots

### ISSUE THREAD

**Issue by visose** [lin-ycv/RobotsExtended#1]
Hi Victor, you can now use this nuget package https://www.nuget.org/packages/Robots.Rhino to make it easier to develop for the Robots plugin. Just add this to your .csproj:
```
<PackageReference Include="Robots.Rhino" Version="1.1.7" />
```
and remove any references to local Robots.dll and Robots.gha files.

**Comment by lin-ycv** [comment]
Thanks! will update accordingly.
